#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Martin's CV
url: "https://cv.inferior.dev"
baseurl: "/" #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic
chrome_mobile_color: #4EAC9E #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-81179759-3

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  blanklines: false
  profile: false
  ignore:
    envs: development
  comments: ["<!-- ", " -->", "#"]
# Development Settings
port: 4000
host: 0.0.0.0
safe: false
gems:
  - jekyll-pdf