name: create PDF file
on: 
  push:
    branches: 
      - gh-pages
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: convert page to pdf
      uses: misaelnieto/web_to_pdf_action@master
      with:
        webPageURL: https://cv.inferior.dev
        outputFile: ./cv_en.pdf
        usePuppeteer: true
        pdfOptions: '{"format": "A4", "margin": {"top": "2.54cm", "left": "2.54cm", "right": "2.54cm", "bottom": "2.54cm"}}'
    - name: commit PDF to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate PDF
        branch: gh-pages
        file_pattern: cv_en.pdf
