name: create PDF file
on: 
  push:
    branches: 
      - gh-pages
  pull_request:
    branches: 
      - gh-pages
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./cv_en.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CV PDF
          path: ./assets/pdf/cv_en.pdf
